### ISSUE TITLE
Need an option for setting --portal-context flag

### ISSUE THREAD

**Issue by MattMNL** [nickthesing/bb-watch-cli#2]
Since we're not using /portalserver in our project: _http://localhost:7777/import/package_

Example of usage in bb-import:
_bb-import package.zip --portal-context /_

**Comment by nickthesing** [comment]
Should be part of the bb-watch repo. Fix will be implementing in https://github.com/nickthesing/bb-watch. Configuration will work through bb-watch-cli-configuration

**Comment by nickthesing** [comment]
PR: https://github.com/nickthesing/bb-watch/pull/17

**Comment by nickthesing** [comment]
Updated in https://github.com/nickthesing/bb-watch/releases/tag/0.2.1
